- Add aggregate job to check if other jobs succeed

diff --git a/.github/workflows/cmake.yaml b/.github/workflows/cmake.yaml
--- a/.github/workflows/cmake.yaml
+++ b/.github/workflows/cmake.yaml
@@ -57,3 +57,18 @@ jobs:
           configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }}']"
           buildPreset: 'ninja-release-${{ matrix.platform.compiler }}-${{ matrix.platform.arch }}'
           testPreset: 'test-release-${{ matrix.platform.compiler }}-${{ matrix.platform.arch }}'
+  all-checks-passed:
+    name: All checks passed
+    if: ${{ always() }}
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check build results
+        if: ${{ needs.build.result != 'success' }}
+        run: |
+          echo "One or more CMake builds failed."
+          exit 1
+
+      - name: All checks passed
+        run: echo "All CMake builds passed!"
+
